version: '3.8'
services:
  airplane_server:
    container_name: airplane_server
    networks:
      static-network:
        ipv4_address: 172.110.130.161
    build:
      context: .
      dockerfile: Dockerfile
    ports: "80:80" 
